#pragma once

#ifndef _WINNT_
#include <ntdef.h>
#endif

#define CLAWSANDBOX_PORT_NAME L"\\ClawSandboxPort"
#define CLAWSANDBOX_PROTOCOL_VERSION 1
#define CLAWSANDBOX_MESSAGE_QUERY_TRACKED_PIDS 1

typedef struct _CLAWSANDBOX_MESSAGE_HEADER
{
    ULONG Version;
    ULONG Message;
} CLAWSANDBOX_MESSAGE_HEADER, *PCLAWSANDBOX_MESSAGE_HEADER;

typedef struct _CLAWSANDBOX_TRACKED_PIDS_REPLY
{
    ULONG Count;
    ULONG Capacity;
    ULONG_PTR ProcessIds[1];
} CLAWSANDBOX_TRACKED_PIDS_REPLY, *PCLAWSANDBOX_TRACKED_PIDS_REPLY;
